# Security (BCrypt encoded client-secret (raw secret: demo))
io.sapl:
  server:
    accesscontrol:
      admin-username: demo
      # plaintext: 'demo' encoded using bcrypt:
      encoded-admin-password: $2y$12$1yBhnA.SfCzTfNrChI/HNuoqz3k/RCG9iXCbQMRje96hnx1DsfPeq

    allowBasicAuth: True

    # Optional: configure API key  authentication
    # List of permitted API Keys that can be used for authentication when the option allowApiKeyAuth is set to ture.
    # --header "API_KEY: phsNZdvQAFX9P2jgGzq9TrzUecQhsnHc"
    allowApiKeyAuth: True

    # Optional: configure Oauth2 (jwt) authentication
    allowOauth2Auth: False

  pdp.embedded:
# The following options enable or disable different levels of logging for decisions.
#
# print-trace: true|false This is the most fine-grained explanation of a decision made
#                         by the PDP each individual calculation step is documented.
#                         The trace is in JSON format and may become very large.
#                         Recommended only as a last resort for troubleshooting.
      print-trace: true
# print-json-report: true|false This is a JSON report summarizing the applied algorithms
#                               and results of each evaluated policy (set) in the
#                               decision-making process. It includes lists of all errors
#                               and values of policy information point attributes
#                               encountered during the evaluation of each policy (set).
      print-json-report: true
# print-text-report: true|false This will log a human-readable textual report based on the
#                               same data as the 'print-json-report' option generates.
      print-text-report: true
# pretty-print-reports: true|false This option can enable formatting of JSON data while
#                                  printing JSON during reporting and tracing.
#                                  If it is intended to copy&paste JSON from the console-log
#                                  it is recommended to keep this turned off.
      pretty-print-reports: false

# Configures Oauth2 JWT Issuer-Uri required when io.sapl.server.allowOauth2Auth is true
spring.security.oauth2.resourceserver.jwt:
  issuer-uri: http://auth-server:8080/default

spring:
  datasource:
    url: jdbc:h2:file:~/sapl/db
    username: sa
    password: password

# Http TLS/SSL configuration
server:
  address: localhost
  port: ${PORT:8443}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:config/keystore.p12
    key-store-password: changeme
    key-password: changeme
    key-alias: netty


# Rsocket configuration
spring.rsocket.server:
  port: ${RSOCKET_PORT:7000}
  transport: tcp
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:config/keystore.p12
    key-store-password: changeme
    key-password: changeme
    key-alias: netty

logging.level:
  #"root": DEBUG
  "[io.sapl]": DEBUG
  "[io.sapl.server.ce]": DEBUG
