#
# Copyright (C) 2017-2024 Dominic Heutelbeck (dominic@heutelbeck.com)
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Security (BCrypt encoded client-secret (raw secret: demo))
io.sapl:
  server:
    accesscontrol:
      admin-username: demo
      # plaintext: 'demo' encoded using argon2:
      encoded-admin-password: $argon2id$v=19$m=15360,t=2,p=1$pZtquF0gUGAmFeEoKJ9sdA9cnsvwWmjLadQMTTl6xJY$PyASWvCQQt33Zm5aOzgBWahTim8smd4LQXLVRJ4dYBSQ/F3M6RGNKIHhyrlPlNXdBmcpdTwvB4ukPUpDK/Q92Q

    allowBasicAuth: True

    # Optional: configure API key  authentication
    # --header "API_KEY: phsNZdvQAFX9P2jgGzq9TrzUecQhsnHc"
    allowApiKeyAuth: True
    apiKeyHeaderName: "API_KEY"
    apiKeyCaching:
      enabled: True
      expire: 300 # seconds
      maxSize: 10000

    # Optional: configure Oauth2 (jwt) authentication
    allowOauth2Auth: True

  pdp.embedded:
# The following options enable or disable different levels of logging for decisions.
#
# print-trace: true|false This is the most fine-grained explanation of a decision made
#                         by the PDP each individual calculation step is documented.
#                         The trace is in JSON format and may become very large.
#                         Recommended only as a last resort for troubleshooting.
      print-trace: true
# print-json-report: true|false This is a JSON report summarizing the applied algorithms
#                               and results of each evaluated policy (set) in the
#                               decision-making process. It includes lists of all errors
#                               and values of policy information point attributes
#                               encountered during the evaluation of each policy (set).
      print-json-report: true
# print-text-report: true|false This will log a human-readable textual report based on the
#                               same data as the 'print-json-report' option generates.
      print-text-report: true
# pretty-print-reports: true|false This option can enable formatting of JSON data while
#                                  printing JSON during reporting and tracing.
#                                  If it is intended to copy&paste JSON from the console-log
#                                  it is recommended to keep this turned off.
      pretty-print-reports: false

# Configures Oauth2 JWT Issuer-Uri required when io.sapl.server.allowOauth2Auth is true
spring.security.oauth2.resourceserver.jwt:
  issuer-uri: http://localhost:9000/realms/SAPL
  
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/saplce
    username: saplce
    password: Test12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect

# Http TLS/SSL configuration
server:
  address: localhost
  port: ${PORT:8443}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:config/keystore.p12
    key-store-password: changeme
    key-password: changeme
    key-alias: netty


# Rsocket configuration
spring.rsocket.server:
  port: ${RSOCKET_PORT:7000}
  transport: tcp
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:config/keystore.p12
    key-store-password: changeme
    key-password: changeme
    key-alias: netty

logging.level:
  #"root": DEBUG
  "[io.sapl]": DEBUG
  "[io.sapl.server.ce]": DEBUG

spring.security.oauth2.client:
  registration:
     keycloak:
       client-id: sapl
#       client-secret: jadajada
       scope: openid
       authorization-grant-type: authorization_code
#       redirect-uri: http://localhost:8443/login/oauth2/keycloak
#   provider:
#     keycloak:
#       issuer-uri: http://localhost:9000/realms/sapl

spring.security.oauth2.client.provider.keycloak:
  issuer-uri: http://localhost:9000/realms/SAPL
  user-name-attribute: preferred_username
