# Security (BCrypt encoded client-secret (raw secret: demo))
io.sapl:
  server:
    admin-username: demo
    encoded-admin-password: "{bcrypt}$2y$12$1yBhnA.SfCzTfNrChI/HNuoqz3k/RCG9iXCbQMRje96hnx1DsfPeq"
# MariaDB
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sapl
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: testdb
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDB53Dialect
# SSL
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeme
    key-password: changeme
    key-alias: netty
