# Security (BCrypt encoded client-secret (raw secret: demo))
io.sapl:
  server:
    admin-username: demo
    encoded-admin-password: "{bcrypt}$2y$12$1yBhnA.SfCzTfNrChI/HNuoqz3k/RCG9iXCbQMRje96hnx1DsfPeq"
# H2
spring:
  h2:
    console.enabled: false
  datasource:
#    url: jdbc:h2:mem:pdp-server-ce.db
    url: jdbc:h2:file:~/sapl/db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    open-in-view: false
# SSL
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeme
    key-password: changeme
    key-alias: netty
