# Security (BCrypt encoded client-secret (raw secret: demo))
io.sapl:
  server:
    admin-username: demo
    encoded-admin-password: $2y$12$1yBhnA.SfCzTfNrChI/HNuoqz3k/RCG9iXCbQMRje96hnx1DsfPeq
  pdp.embedded:
# The following options enable or disable different levels of logging for decisions.
#
# print-trace: true|false This is the most fine-grained explanation of a decision made
#                         by the PDP each individual calculation step is documented.
#                         The trace is in JSON format and may become very large.
#                         Recommended only as a last resort for troubleshooting.
      print-trace: true
# print-json-report: true|false This is a JSON report summarizing the applied algorithms
#                               and results of each evaluated policy (set) in the decision
#                               making process. It includes lists of all errors and values
#                               of policy information point attributes encountered
#                               during the evaluation of each policy (set).
      print-json-report: true
# print-text-report: true|false This will log a human readable textual report based on the
#                               same data as the 'print-json-report' option generates.
      print-text-report: true
# pretty-print-reports: true|false This option can enable formatting of JSON data while
#                                  printing JSON during reporting and tracing.
#                                  If it is intended to copy&paste JSON from the console-log
#                                  it is recommended to keep this turned off.
      pretty-print-reports: false

# H2
spring:
  h2:
    console.enabled: false
  datasource:
    url: jdbc:h2:file:~/sapl/db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    open-in-view: false
# SSL
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:keystore.p12
#    key-store-password: changeme
#    key-password: changeme
#    key-alias: netty
logging.level:
  "[io.sapl]": TRACE
  "[io.sapl.server.ce]": INFO
 