name: build

on:
  workflow_dispatch:
  push:
    branches: [main]
  repository_dispatch:
    branches: [main]
  
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        lfs: true
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
        cache: 'maven'
      
  #  - name: Set up Node.js
  #    uses: actions/setup-node@v3
  #    with:
  #      node-version: '18'
    
    - name: Build with Maven (JUnit, JaCoCo, Sonar) 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:RELEASE:sonar -Dsonar.host.url=https://sonar.ftk.de -Dsonar.login=${SONAR_TOKEN} -P production

    - name: Build SAPL Server CE Docker image
      run: mvn -B clean spring-boot:build-image -pl sapl-server-ce -P docker,production -DskipTests
                 
    - name: Clean up local repository before caching
      run: rm -rf /.m2/repository/io/sapl
