name: build

on:
  workflow_dispatch:
  push:
    branches: [main]
  repository_dispatch:
    branches: [main]
  
jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Check out
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        lfs: true
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
      with:
        distribution: 'adopt'
        java-version: 17
        cache: 'maven'
       
    - name: Build with Maven (JUnit, JaCoCo, Sonar) 
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:RELEASE:sonar -Dsonar.host.url=https://sonar.ftk.de -Dsonar.login=${{ secrets.SONAR_TOKEN }} -P production

    - name: Build SAPL Server CE Docker image
      run: mvn -B clean spring-boot:build-image -pl sapl-server-ce -P docker,production -DskipTests -Dspring-boot.build-image.publish=true -Ddocker.credentials.username=${{ secrets.GHUB_USERNAME }} -Ddocker.credentials.password=${{ secrets.GHUB_ACCESS_TOKEN }}
                 
    - name: Clean up local repository before caching
      run: rm -rf /.m2/repository/io/sapl
